# Generated by Django 2.2.7 on 2019-11-12 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'OEMs',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('coremultiplier', models.CharField(choices=[('u', 'Unlocked'), ('l', 'Locked')], max_length=1)),
                ('release_date', models.DateField()),
                ('price', models.PositiveIntegerField(help_text='in Euros')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.OEM')),
            ],
        ),
    ]
