# Generated by Django 2.2.7 on 2019-11-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_delete_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name_plural': 'CPUs'},
        ),
    ]
